"""A UCI engine as an arena agent. Generated by tools/uci_opponent.py."""

import atexit
import json
import os
from pathlib import Path

import chess
import chess.engine

_HERE = Path(__file__).resolve().parent
_CFG = json.loads((_HERE / "engine.json").read_text(encoding="utf-8"))

# Wall-clock milliseconds held back from whatever we tell the engine it has.
# harness/sandbox.py kills the agent at time_left_ms + WATCHDOG_GRACE_MS, and
# harness/referee.py flags it the moment its clock goes negative, so the margin
# has to cover engine time-manager overshoot plus this process's own overhead.
_SAFETY_MS = int(_CFG.get("safety_ms", 150))
_MIN_MS = int(_CFG.get("min_ms", 10))
_INCREMENT_MS = int(_CFG.get("increment_ms", 0))


def _kill_with_me(pid: int) -> object | None:
    """Tie a child's lifetime to ours, so a killed agent leaves no engine behind."""
    if os.name != "nt":
        return None
    import ctypes
    from ctypes import wintypes

    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)

    class _Limits(ctypes.Structure):
        _fields_ = [
            ("PerProcessUserTimeLimit", ctypes.c_int64),
            ("PerJobUserTimeLimit", ctypes.c_int64),
            ("LimitFlags", wintypes.DWORD),
            ("MinimumWorkingSetSize", ctypes.c_size_t),
            ("MaximumWorkingSetSize", ctypes.c_size_t),
            ("ActiveProcessLimit", wintypes.DWORD),
            ("Affinity", ctypes.POINTER(ctypes.c_ulong)),
            ("PriorityClass", wintypes.DWORD),
            ("SchedulingClass", wintypes.DWORD),
        ]

    class _Extended(ctypes.Structure):
        _fields_ = [
            ("BasicLimitInformation", _Limits),
            ("IoInfo", ctypes.c_byte * 48),
            ("ProcessMemoryLimit", ctypes.c_size_t),
            ("JobMemoryLimit", ctypes.c_size_t),
            ("PeakProcessMemoryUsed", ctypes.c_size_t),
            ("PeakJobMemoryUsed", ctypes.c_size_t),
        ]

    job = kernel32.CreateJobObjectW(None, None)
    if not job:
        return None
    info = _Extended()
    info.BasicLimitInformation.LimitFlags = 0x2000  # KILL_ON_JOB_CLOSE
    if not kernel32.SetInformationJobObject(job, 9, ctypes.byref(info), ctypes.sizeof(info)):
        return None
    handle = kernel32.OpenProcess(0x0100 | 0x0001, False, pid)  # SET_QUOTA | TERMINATE
    if not handle:
        return None
    kernel32.AssignProcessToJobObject(job, handle)
    kernel32.CloseHandle(handle)
    return job  # held for the life of the process; closing it kills the engine


_command = [_CFG["exe"], *_CFG.get("args", [])]
_engine = chess.engine.SimpleEngine.popen_uci(
    _command,
    timeout=float(_CFG.get("startup_timeout_s", 30.0)),
    cwd=_CFG.get("cwd") or str(Path(_CFG["exe"]).resolve().parent),
)
# Slack python-chess allows on top of the search limit before it gives up on a
# reply. Kept under the referee's own patience so a hung engine loses cleanly.
_engine.timeout = float(_CFG.get("reply_slack_s", 5.0))
if _CFG.get("options"):
    _engine.configure(_CFG["options"])
_JOB = _kill_with_me(_engine.transport.get_pid())


def _shutdown() -> None:
    # Kill rather than `close()`: a clean shutdown waits for the engine to
    # answer `quit`, and an engine that has stopped listening would hang the
    # exit. The job object above is what actually guarantees no survivors.
    try:
        _engine.transport.kill()
    except Exception:
        pass


atexit.register(_shutdown)

_GAME = object()  # a stable token, so python-chess sends `ucinewgame` exactly once
_root: chess.Board | None = None
_moves: list[chess.Move] = []


def _sync(fen: str) -> chess.Board:
    """Rebuild the played line, so the engine keeps its repetition detection.

    We are asked to move only on our own turn, so consecutive calls are two
    plies apart -- our last move, then the opponent's reply. Searching those two
    plies for a position matching the FEN recovers both moves. If nothing
    matches (first call of the game, or an arena that jumps around), the line
    restarts from this position and only repetition history is lost.
    """
    global _root, _moves
    target = chess.Board(fen)
    if _root is not None:
        board = _root.copy()
        for played in _moves:
            board.push(played)
        if board.fen() == target.fen():
            return board
        for ours in list(board.legal_moves):
            board.push(ours)
            if board.fen() == target.fen():
                _moves.append(ours)
                return board
            for theirs in list(board.legal_moves):
                board.push(theirs)
                if board.fen() == target.fen():
                    _moves.extend([ours, theirs])
                    return board
                board.pop()
            board.pop()
    _root = chess.Board(fen)
    _moves = []
    return _root.copy()


def _limit(time_left_ms: int) -> chess.engine.Limit:
    budget_ms = max(_MIN_MS, time_left_ms - _SAFETY_MS)
    if _CFG.get("nodes"):
        return chess.engine.Limit(nodes=int(_CFG["nodes"]))
    if _CFG.get("depth"):
        return chess.engine.Limit(depth=int(_CFG["depth"]))
    if _CFG.get("movetime_ms"):
        return chess.engine.Limit(time=min(int(_CFG["movetime_ms"]), budget_ms) / 1000.0)
    # Hand the engine a clock rather than a per-move budget, so its own time
    # manager runs. That manager is part of the strength the rating lists
    # measured, and replacing it with a fixed movetime would measure a
    # different engine. The opponent's clock is unknown, so it is mirrored.
    return chess.engine.Limit(
        white_clock=budget_ms / 1000.0,
        black_clock=budget_ms / 1000.0,
        white_inc=_INCREMENT_MS / 1000.0,
        black_inc=_INCREMENT_MS / 1000.0,
    )


def get_move(fen: str, time_left_ms: int) -> str:
    board = _sync(fen)
    result = _engine.play(board, _limit(time_left_ms), game=_GAME)
    move = result.move
    if move is None:  # `bestmove (none)`, or a resignation-style reply
        move = next(iter(board.legal_moves))
    _moves.append(move)
    return move.uci()
